version: "3.9"

services:
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: libuser
      POSTGRES_PASSWORD: libpass
      POSTGRES_DB: libdb
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - backend-net

  backend:
    image: lib-backend:latest
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_NAME: libdb
      DB_USER: libuser
      DB_PASSWORD: libpass
    networks:
      - backend-net

  adminer:
    image: adminer:4
    environment:
      ADMINER_DEFAULT_SERVER: db
    ports:
      - "8080:8080"
    networks:
      - backend-net

  frontend:
    image: lib-frontend:latest
    networks:
      - backend-net

  reverse-proxy:
    image: lib-proxy:latest
    # если у тебя в compose сейчас "8088:80" — поставь тут так же
    ports:
      - "8088:80"
    networks:
      - backend-net

volumes:
  db_data:

networks:
  backend-net:
