name: CD

on:
  push:
    branches: [ main ]
  workflow_dispatch:

env:
  REGISTRY: ghcr.io
  IMAGE_OWNER: shinonomeri   # твой логин на GitHub в нижнем регистре

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push backend image
        run: |
          IMAGE=${{ env.REGISTRY }}/${{ env.IMAGE_OWNER }}/lib-backend:latest
          docker build -t $IMAGE ./backend
          docker push $IMAGE

      - name: Build and push frontend image
        run: |
          IMAGE=${{ env.REGISTRY }}/${{ env.IMAGE
